#!/bin/bash

git clone https://github.com/AMReX-Codes/amrex.git
cd amrex
git checkout development
mkdir builddir
cd builddir

export CC=x86_64-conda_cos6-linux-gnu-gcc
export CXX=x86_64-conda_cos6-linux-gnu-g++
export FC=x86_64-conda_cos6-linux-gnu-gfortran
cmake .. -DBUILD_SHARED_LIBS=ON -DAMReX_MPI=NO
make install

cd ../Docs/Doxygen
sed -i 's/GENERATE_TAGFILE       =/GENERATE_TAGFILE = amrex.tag/' doxygen.conf
doxygen doxygen.conf
cp amrex.tag /srv/conda/envs/notebook/share/xeus-cling/tagfiles/
mv ~/amrex.json /srv/conda/envs/notebook/etc/xeus-cling/tags.d/
